import { Card } from "@/components/ui/card"
import type { AttributionData } from "@/lib/attribution"

export type SummaryWithAttributionProps = {
    content: string
    attribution: AttributionData
}

export function SummaryWithAttribution({ content, attribution }: SummaryWithAttributionProps) {
    return (
        <Card className="p-6">
            <div className="prose prose-sm max-w-none dark:prose-invert">
                <div className="whitespace-pre-wrap leading-relaxed">{content}</div>
            </div>

            <div className="mt-6 border-t pt-6">
                <p className="text-sm font-semibold text-muted-foreground">Content Attribution</p>
                <div className="mt-3 space-y-2 text-sm">
                    <p>
                        <span className="font-medium">Episode:</span> {attribution.episodeTitle}
                    </p>
                    <p>
                        <span className="font-medium">Podcast:</span> {attribution.podcastTitle}
                    </p>
                    <p>
                        <span className="font-medium">Creator:</span> {attribution.creatorName}
                    </p>
                    {attribution.creatorWebsite && (
                        <p>
                            <span className="font-medium">Website:</span>{" "}
                            <a
                                href={attribution.creatorWebsite}
                                className="text-primary hover:underline"
                                target="_blank"
                                rel="noopener noreferrer"
                            >
                                {attribution.creatorWebsite}
                            </a>
                        </p>
                    )}
                    <p className="pt-2">
                        <a
                            href={attribution.episodeUrl}
                            className="font-medium text-primary hover:underline"
                            target="_blank"
                            rel="noopener noreferrer"
                        >
                            Listen to the full episode →
                        </a>
                    </p>
                    <p className="pt-2 text-xs text-muted-foreground">
                        Generated by Podslice on {attribution.generatedAt.toLocaleDateString()}
                    </p>
                </div>
            </div>
        </Card>
    )
}
