export type AttributionData = {
    podcastTitle: string
    episodeTitle: string
    episodeUrl: string
    creatorName: string
    creatorWebsite?: string
    generatedAt: Date
}

export function generateAttributionText(data: AttributionData): string {
    const lines = [
        `Content generated from: ${data.episodeTitle}`,
        `Podcast: ${data.podcastTitle}`,
        `Creator: ${data.creatorName}`,
    ]

    if (data.creatorWebsite) {
        lines.push(`Website: ${data.creatorWebsite}`)
    }

    lines.push(
        `Listen to the full episode: ${data.episodeUrl}`,
        `Generated by PODSLICE.Ai Studio on ${data.generatedAt.toLocaleDateString()}`,
    )

    return lines.join("\n")
}

export function generateAttributionHTML(data: AttributionData): string {
    return `
    <div class="podslice-attribution" style="margin-top: 1.5rem; padding: 1rem; border-top: 2px solid #e5e7eb; font-size: 0.875rem; color: #6b7280;">
      <p style="margin: 0 0 0.5rem 0; font-weight: 600;">Content Attribution</p>
      <p style="margin: 0 0 0.25rem 0;">
        <strong>Episode:</strong> ${data.episodeTitle}
      </p>
      <p style="margin: 0 0 0.25rem 0;">
        <strong>Podcast:</strong> ${data.podcastTitle}
      </p>
      <p style="margin: 0 0 0.25rem 0;">
        <strong>Creator:</strong> ${data.creatorName}
      </p>
      ${data.creatorWebsite
            ? `
        <p style="margin: 0 0 0.25rem 0;">
          <strong>Website:</strong> <a href="${data.creatorWebsite}" style="color: #2563eb; text-decoration: underline;">${data.creatorWebsite}</a>
        </p>
      `
            : ""
        }
      <p style="margin: 0.5rem 0 0.25rem 0;">
        <a href="${data.episodeUrl}" style="color: #2563eb; text-decoration: underline; font-weight: 500;">
          Listen to the full episode →
        </a>
      </p>
      <p style="margin: 0.5rem 0 0 0; font-size: 0.75rem; color: #9ca3af;">
        Generated by PODSLICE.Ai Studio on ${data.generatedAt.toLocaleDateString()}
      </p>
    </div>
  `
}

export function generateSocialAttribution(
    data: AttributionData,
    platform: "twitter" | "linkedin" | "instagram",
): string {
    const baseText = `\n\n🎙️ From "${data.episodeTitle}" by ${data.creatorName}`

    switch (platform) {
        case "twitter":
            return `${baseText}\n\nListen: ${data.episodeUrl}\n\n#Podcast #${data.podcastTitle.replace(/\s+/g, "")}`
        case "linkedin":
            return `${baseText}\n\nListen to the full episode: ${data.episodeUrl}\n\n#Podcasts #ContentCreation`
        case "instagram":
            return `${baseText}\n\nLink in bio to listen!\n\n#podcast #${data.podcastTitle.replace(/\s+/g, "").toLowerCase()}`
    }
}
